<a href="https://colab.research.google.com/github/ddtechdd/MLDA-LAB/blob/main/HirerachialClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import AgglomerativeClustering
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from scipy.optimize import linear_sum_assignment

# Load data
iris = load_iris()
x = iris.data[:, :2]  # Use only first two features for visualization
y = iris.target

# Split data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Apply Agglomerative Clustering
hc_model = AgglomerativeClustering(n_clusters=3, linkage='ward')
y_hc = hc_model.fit_predict(x_test)

# Align cluster labels with true labels using Hungarian algorithm
def match_labels(true_labels, cluster_labels):
    cm = confusion_matrix(true_labels, cluster_labels)
    row_ind, col_ind = linear_sum_assignment(-cm)
    mapping = {col: row for row, col in zip(row_ind, col_ind)}
    return np.array([mapping[label] for label in cluster_labels])

y_hc_aligned = match_labels(y_test, y_hc)

# Evaluation
print("Classification Report:\n", classification_report(y_test, y_hc_aligned))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_hc_aligned))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.88      0.78      0.82         9
           2       0.83      0.91      0.87        11

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

Confusion Matrix:
 [[10  0  0]
 [ 0  7  2]
 [ 0  1 10]]
